Refactor: Improve Glue job temp dir and error logging
Co-authored-by: kgemera123 <kgemera123@gmail.com>

diff --git a/.github/workflows/deploy_glue.yml b/.github/workflows/deploy_glue.yml
--- a/.github/workflows/deploy_glue.yml
+++ b/.github/workflows/deploy_glue.yml
@@ -103,6 +103,10 @@ jobs:
       # --------------------------------------------------
       - name: Create or Update AWS Glue Job Definitions
         run: |
+          TEMP_BUCKET=${{ secrets.S3_BUCKET_TEMP }}
+          if [ -z "$TEMP_BUCKET" ]; then
+            TEMP_BUCKET=cmjm-datalake
+          fi
           # Job para dim_customer
           JOB_NAME="sakila-etl-dim-customer"
           SCRIPT_PATH=${{ env.DIM_CUSTOMER_SCRIPT }}
@@ -126,12 +130,12 @@ jobs:
                 "--job-bookmark-option": "job-bookmark-enable",
                 "--enable-metrics": "true",
                 "--enable-continuous-cloudwatch-log": "true",
-                "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/",
+                "--TempDir": "s3://""$TEMP_BUCKET""/glue/temp/",
                 "--enable-s3-parquet-optimized-committer": "true"
               }
             }'
           else
-            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
+            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://'$TEMP_BUCKET'/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
           fi
 
           # Job para dim_film
@@ -157,12 +161,12 @@ jobs:
                 "--job-bookmark-option": "job-bookmark-enable",
                 "--enable-metrics": "true",
                 "--enable-continuous-cloudwatch-log": "true",
-                "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/",
+                "--TempDir": "s3://""$TEMP_BUCKET""/glue/temp/",
                 "--enable-s3-parquet-optimized-committer": "true"
               }
             }'
           else
-            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
+            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://'$TEMP_BUCKET'/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
           fi
 
           # Job para dim_store
@@ -188,12 +192,12 @@ jobs:
                 "--job-bookmark-option": "job-bookmark-enable",
                 "--enable-metrics": "true",
                 "--enable-continuous-cloudwatch-log": "true",
-                "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/",
+                "--TempDir": "s3://""$TEMP_BUCKET""/glue/temp/",
                 "--enable-s3-parquet-optimized-committer": "true"
               }
             }'
           else
-            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
+            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://'$TEMP_BUCKET'/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
           fi
 
           # Job para dim_date
@@ -243,12 +247,12 @@ jobs:
                 "--job-bookmark-option": "job-bookmark-enable",
                 "--enable-metrics": "true",
                 "--enable-continuous-cloudwatch-log": "true",
-                "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/",
+                "--TempDir": "s3://""$TEMP_BUCKET""/glue/temp/",
                 "--enable-s3-parquet-optimized-committer": "true"
               }
             }'
           else
-            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://${{ secrets.S3_BUCKET_TEMP }}/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
+            aws glue create-job --name $JOB_NAME --role ${{ secrets.AWS_GLUE_ROLE_ARN }} --region ${{ secrets.AWS_REGION }} --command Name=glueetl,ScriptLocation=$SCRIPT_PATH,PythonVersion=3 --glue-version 3.0 --number-of-workers 2 --worker-type G.1X --connections '{"Connections": ["Jdbc connection"]}' --default-arguments '{"--job-bookmark-option": "job-bookmark-enable", "--enable-metrics": "true", "--enable-continuous-cloudwatch-log": "true", "--TempDir": "s3://'$TEMP_BUCKET'/glue/temp/", "--enable-s3-parquet-optimized-committer": "true"}'
           fi
 
       # --------------------------------------------------
@@ -291,6 +295,16 @@ jobs:
 
             if [ "$STATE" != "SUCCEEDED" ]; then
               echo "Error: El job $JOB_NAME falló con estado $STATE"
+              # Mostrar mensaje de error del JobRun
+              ERR_MSG=$(aws glue get-job-run --job-name "$JOB_NAME" --run-id "$JOB_RUN_ID" --region ${{ secrets.AWS_REGION }} --query 'JobRun.ErrorMessage' --output text)
+              echo "Glue ErrorMessage: $ERR_MSG"
+              # Intentar imprimir los últimos logs de CloudWatch para ayuda de debugging
+              set +e
+              echo "-> Últimos logs de CloudWatch (output):"
+              aws logs get-log-events --log-group-name /aws-glue/jobs/output --log-stream-name "$JOB_NAME/$JOB_RUN_ID" --limit 50 --region ${{ secrets.AWS_REGION }} --output text || true
+              echo "-> Últimos logs de CloudWatch (error):"
+              aws logs get-log-events --log-group-name /aws-glue/jobs/error --log-stream-name "$JOB_NAME/$JOB_RUN_ID" --limit 50 --region ${{ secrets.AWS_REGION }} --output text || true
+              set -e
               exit 1
             fi
             echo "Job $JOB_NAME completado exitosamente"
